version: "3.1"

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - db-network
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - db-network
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  mongodb:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/bitnami/mongodb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
